name : Validate Data

on:
  push:
  pull_request
jobs:
  validate-data:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
          cache-dependency-path: script/validate-data/package-lock/package.json

      - name: Validate: Validate workflows
        run: |
          npn ci
          npx ts-node-script ./index.ts
        working-directory: ./script/validate-data
